TWITTER_BEARER_TOKEN = 'XXXXXXXXXXXXXXXXXXXXXXXXXXXX'

TWITTER_CONSUMER_KEY = 'XXXXXXXXXXXXXXXXXXXXXXXXXXXX'
TWITTER_CONSUMER_SECRET = 'XXXXXXXXXXXXXXXXXXXXXXXXXXXX'
TWITTER_ACCESS_TOKEN = 'XXXXXXXXXXXXXXXXXXXXXXXXXXXX'
TWITTER_ACCESS_TOKEN_SECRET = 'XXXXXXXXXXXXXXXXXXXXXXXXXXXX'

RAPID_API_KEY = 'XXXXXXXXXXXXXXXXXXXXXXXXXXXX'
